site_name: "uvk: Fully-isolated IPython kernel through uv"
theme: readthedocs
nav:
  - About: about.md
  - Installation: install.md
  - Tutorial: Tutorial.ipynb
  - How to?:
    - Author a notebook that is easiest to share: howto/notebook-easiest-to-share.md
    - uvk kernels for multiple Python versions: howto/uvk-multiple-pythons.md
  - Deep dives:
    - "uv, uvkernel and uvk: which for what?": deepdives/uv-uvkernel-uvk.md
  - Reference:
    - The uvk command-line tool: reference/uvk_cli.md
    - The uvk IPython extension: reference/uvk_ext.md
  - Everything else:
    - GitHub: https://github.com/hamelin/uvk/
    - License (MIT): license.md
markdown_extensions:
  - admonition
  - toc:
      permalink: "#"
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: true
      execute: false
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            docstring_section_style: table
            merge_init_into_class: false
            relative_crossrefs: true
            scoped_crossrefs: true
            unwrap_annotated: true
            filters: public
            inherited_members: true
            summary: true
            heading_level: 3
            parameter_headings: true
            type_parameter_headings: true
            show_root_full_path: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            line_length: 88
            separate_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            backlinks: tree
            show_bases: false
            show_inheritance_diagram: false
